### ISSUE TITLE
Wizard. Поведение при сохранении relation.

### ISSUE THREAD

**Issue by svkc** [skvn/crud#27]
Для hasMany при сохранении родительского объекта нужно 2 варианта поведения.
1. nullify
2. destroy
Пусть параметр в конфиге называется cascade

**Comment by vniko** [comment]
Наверное для hasOne тоже надо?
Cascade это же и есть delete
Может по аналогии с sql сделать
имя ключа - 
**on_delete**
Значения
- set_null
- cascade

**Comment by svkc** [comment]
Без разницы.
Тогда реализацию поправь. Оно уже работает.
